services:
  kafka:
    image: apache/kafka:4.1.1
    ports:
      - "9092:9092"
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: docgen
      POSTGRES_USER: docgen
      POSTGRES_PASSWORD: docgen
    profiles: ["full"]
  docapi:
    build:
      context: .
      dockerfile: doc-api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/docgen
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    profiles: ["full"]
    depends_on:
      - kafka
      - postgres
  doc-renderer:
    build:
      context: .
      dockerfile: doc-renderer/Dockerfile
    ports:
      - "8081:8081"
    profiles: ["full"]
