server:
  port: 8080

spring:
  application:
    name: DocApi
  datasource:
    url: jdbc:postgresql://localhost:5432/docgen
    username: docgen
    password: docgen
  flyway:
    enabled: true
    locations: classpath:db/migration
    placeholder-replacement: false

management:
  endpoints:
    web:
      exposure:
        include: health, info